#City of Philadelphia Licenses and Inspections Appeals

The dataset contains decisions of Philadelphia Licenses and Inspections Appeal Board. The dataset contains 28869 records and 37 columns.

Several columns such as Appeal Grounds, Related Permits and Proviso are in Natural Language format. 

Source: https://www.opendataphilly.org/dataset/license-and-inspections-appeals/resource/b721ad52-9e27-46d2-b494-6bf0ef1c7603?inner_span=True

### I would like to research the relationship of the board decision stored in the column 'decision' and other values in the dataset such as Appeal Grounds(NL), Related Permits(NL), Proviso(NL) and well as property address(geospatial).

In [1]:
#load python packages
import os
import pandas as pd
import datetime
import seaborn as sns
#import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
from pandas_profiling import ProfileReport

In [2]:
#Database URL
url = 'https://phl.carto.com/api/v2/sql?q=SELECT+*,+ST_Y(the_geom)+AS+lat,+ST_X(the_geom)+AS+lng+FROM+appeals&filename=appeals&format=csv&skipfields=cartodb_id'
df = pd.read_csv(url)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (5,15,16,22,25) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df.head()

,the_geom,the_geom_webmercator,objectid,addressobjectid,address,unit_type,unit_num,zip,opa_account_num,parcel_id_num,...,scheduleddate,decision,meetingresult,proviso,decisiondate,systemofrecord,geocode_x,geocode_y,lat,lng
0,0101000020E610000037BAFB2B1DC352C040158AB3C90A...,0101000020110F000083B7668792DE5FC1DB531E50DD9B...,8,716319.0,8940 KREWSTOWN RD,NaN,118,19115-4517,888630077.0,NaN,...,2010-05-04 13:15:00,MOOT,NaN,COMPLIED,2010-05-04 00:00:00,HANSEN,2.724252e+06,285119.162422,40.084280,-75.048656
1,0101000020E61000003790253716C852C073EBA50163FD...,0101000020110F000090D1ECEB04E75FC16E10A3FAFF8C...,9,628798.0,2300 E YORK ST,NaN,NaN,19125-2120,313145500.0,NaN,...,2009-10-28 17:00:00,GRANTED,NaN,NaN,2009-10-28 00:00:00,HANSEN,2.703654e+06,246341.440497,39.979584,-75.126356
2,0101000020E61000003D08EF26A0CB52C040DF48F08D06...,0101000020110F0000E96105BF07ED5FC1EFBBD9912A97...,10,531963.0,128 E SHARPNACK ST,NaN,NaN,19119-2237,221108000.0,NaN,...,2009-12-29 13:15:00,MOOT,NaN,COMPLIED,2009-12-30 00:00:00,HANSEN,2.687406e+06,271965.871360,40.051207,-75.181650
3,0101000020E61000000E3A31E95AC552C003F006071902...,0101000020110F000085E81E1561E25FC17705D2083992...,11,297984.0,4671 FRANKFORD AVE,NaN,NaN,19124-5827,871529760.0,NaN,...,2009-10-06 09:30:00,GRANTED,NaN,NaN,2009-10-06 00:00:00,HANSEN,2.715205e+06,260100.891162,40.016389,-75.083674
4,0101000020E6100000936D2397A0CE52C066D5D7D893FB...,0101000020110F0000AA96150421F25FC1630150B0FE8A...,12,589254.0,5421 VINE ST,NaN,NaN,19139-2041,41034400.0,NaN,...,2009-12-29 13:15:00,WITHDRAWN,NaN,NaN,2009-10-21 00:00:00,HANSEN,2.675173e+06,240360.419544,39.965449,-75.228552

In [4]:
print("df.shape", df.shape)

df.shape (28869, 37)

In [5]:
df.columns

Index(['the_geom', 'the_geom_webmercator', 'objectid', 'addressobjectid',
       'address', 'unit_type', 'unit_num', 'zip', 'opa_account_num',
       'parcel_id_num', 'censustract', 'opa_owner', 'primaryappellant',
       'appellanttype', 'internaljobid', 'appealnumber', 'acceleratedappeal',
       'createddate', 'completeddate', 'relatedpermit', 'relatedcasefile',
       'appealstatus', 'appealtype', 'agendadescription', 'applicationtype',
       'meetingnumber', 'appealgrounds', 'scheduleddate', 'decision',
       'meetingresult', 'proviso', 'decisiondate', 'systemofrecord',
       'geocode_x', 'geocode_y', 'lat', 'lng'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28869 entries, 0 to 28868
Data columns (total 37 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   the_geom              28275 non-null  object
 1   the_geom_webmercator  28275 non-null  object
 2   objectid              28869 non-null  int64
 3   addressobjectid       28304 non-null  float64
 4   address               28291 non-null  object
 5   unit_type             3 non-null      object
 6   unit_num              471 non-null    object
 7   zip                   28291 non-null  object
 8   opa_account_num       27193 non-null  float64
 9   parcel_id_num         92 non-null     float64
 10  censustract           28275 non-null  float64
 11  opa_owner             27872 non-null  object
 12  primaryappellant      28869 non-null  object
 13  appellanttype         28869 non-null  object
 14  internaljobid         28764 non-null  float64
 15  appealnumber          28869 non-null  object
 16  acceleratedappeal     105 non-null    object
 17  createddate           28869 non-null  object
 18  completeddate         12041 non-null  object
 19  relatedpermit         28783 non-null  object
 20  relatedcasefile       0 non-null      float64
 21  appealstatus          28869 non-null  object
 22  appealtype            105 non-null    object
 23  agendadescription     0 non-null      float64
 24  applicationtype       28869 non-null  object
 25  meetingnumber         105 non-null    object
 26  appealgrounds         28866 non-null  object
 27  scheduleddate         28818 non-null  object
 28  decision              27062 non-null  object
 29  meetingresult         0 non-null      float64
 30  proviso               12128 non-null  object
 31  decisiondate          27579 non-null  object
 32  systemofrecord        28869 non-null  object
 33  geocode_x             28275 non-null  float64
 34  geocode_y             28275 non-null  float64
 35  lat                   28275 non-null  float64
 36  lng                   28275 non-null  float64
dtypes: float64(12), int64(1), object(24)
memory usage: 8.1+ MB

In [7]:
df.nunique()/df.shape[0]

the_geom                0.775884
the_geom_webmercator    0.775884
objectid                1.000000
addressobjectid         0.785687
address                 0.778759
unit_type               0.000069
unit_num                0.004191
zip                     0.465759
opa_account_num         0.751117
parcel_id_num           0.003187
censustract             0.013232
opa_owner               0.682116
primaryappellant        0.452769
appellanttype           0.000242
internaljobid           0.996363
appealnumber            1.000000
acceleratedappeal       0.000069
createddate             0.998545
completeddate           0.417022
relatedpermit           0.977415
relatedcasefile         0.000000
appealstatus            0.000104
appealtype              0.000104
agendadescription       0.000000
applicationtype         0.000139
meetingnumber           0.003637
appealgrounds           0.918736
scheduleddate           0.173127
decision                0.000935
meetingresult           0.000000
proviso                 0.234819
decisiondate            0.070976
systemofrecord          0.000069
geocode_x               0.776646
geocode_y               0.776577
lat                     0.775884
lng                     0.775884
dtype: float64

In [8]:
df.describe()

,objectid,addressobjectid,opa_account_num,parcel_id_num,censustract,internaljobid,relatedcasefile,agendadescription,meetingresult,geocode_x,geocode_y,lat,lng
count,28869.000000,2.830400e+04,2.719300e+04,92.000000,28275.000000,2.876400e+04,0.0,0.0,0.0,2.827500e+04,28275.000000,28275.000000,28275.000000
mean,14435.000000,6.854362e+05,5.427200e+08,250070.847826,249.020878,1.638010e+06,NaN,NaN,NaN,2.695878e+06,247853.193500,39.984351,-75.153914
std,8333.906797,5.612771e+06,3.138668e+08,154006.644163,924.772483,6.122238e+05,NaN,NaN,NaN,1.432669e+04,16486.756321,0.044636,0.052058
min,1.000000,1.054000e+03,1.100411e+07,919.000000,1.000000,5.931420e+05,NaN,NaN,NaN,2.662259e+06,209342.743032,39.880338,-75.274212
25%,7218.000000,2.972160e+05,2.721319e+08,129973.500000,42.020000,1.105569e+06,NaN,NaN,NaN,2.688661e+06,234534.650968,39.948454,-75.180381
50%,14435.000000,4.699440e+05,5.211173e+08,252898.000000,149.000000,1.614060e+06,NaN,NaN,NaN,2.694292e+06,244525.879575,39.975542,-75.160047
75%,21652.000000,6.312012e+05,8.810688e+08,364571.750000,257.000000,2.196362e+06,NaN,NaN,NaN,2.701297e+06,260270.575017,40.018002,-75.134201
max,28869.000000,1.723989e+08,8.886800e+08,597673.000000,9891.000000,2.671235e+06,NaN,NaN,NaN,2.748649e+06,304628.565411,40.137052,-74.961283

In [9]:
#Breakdown by decision
df['decision'].value_counts()

GRANTED         8479
GRANTED/PROV    6303
WITHDRAWN       2437
MOOT            2284
AFFIRMED        1958
DENIED          1822
APPROVED        1557
DISMISSED        945
CONTINUED        556
SUSTAINED        259
HELD/INFO        103
HELD              97
DENIED/PROV       71
ADMIN/REVIEW      63
DISMI/ENFORC      42
REMAND            38
CONT/POST         13
NEWHEARNOT        12
BOARDAKNOWL        7
REFUSED            3
LATE-APPRVD        3
NEWHEARYES         2
LATE-DENIED        2
REVISED            2
RESCHEDULE         2
ISSUED             1
Continued          1
Name: decision, dtype: int64

In [10]:
df['appealgrounds'].value_counts()

PERMIT FOR TWO (2) FAMILY DWELLING IN AN EXISTING STRUCTURE.                                                                                                                                                                                                                                                                                                                                                                                                                              133
PERMIT FOR A TWO (2) FAMILY DWELLING IN AN EXISTING STRUCTURE.                                                                                                                                                                                                                                                                                                                                                                                                                             67
PERMIT FOR THREE (3) FAMILY DWELLING (MULTI-FAMILY DWELLING) IN AN EXISTING STRUCTURE.                                                                                                                                                                                                                                                                                                                                                                                                     65
WE ARE APPEALING THE ISSUANCE OF BUILDING PERMIT #765070 FOR HEALTH AND ENVIRONMENTAL CONCERNS.                                                                                                                                                                                                                                                                                                                                                                                            63
PERMIT FOR A TWO(2) FAMILY DWELLING.                                                                                                                                                                                                                                                                                                                                                                                                                                                       57
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ...
ON 07/01/09 THE DEPARTMENT OF LICENSES AND INSPECTIONS ISSUED REFUSAL OF PERMIT FOR APPLICATION # 194304                                                                                                                                                                                                                                                                                                                                                                                    1
WE DO NOT CLEARLY UNDERSTAND, WHY WE ARE RESPONSIBLE TO REPAIR WHOLE OR PART OF THIS WALL. WHO DETERMINES THE PORTIONS FAIRLY DUE EACH HOME OWNER, WITHOUT THEIR CLEAR UNDERSTANDING.                                                                                                                                                                                                                                                                                                       1
PERMIT FOR THE DEMOLITION OF AN EXISTING REAR STAIR AND FOR THE ERECTION OF A ONE STORY STAIR ADDITION AT THE FIRST FLOOR REAR (NTE 35' HIGH)  AS PART OF AN EXISTING TWO STORY ATTACHED STRUCTURE (INCLUDING A CELLAR) WITH AN EXISTING HOUSE OF WORSHIP ON THE FIRST FLOOR WITH ACCESSORY MEETING ROOM, ACC. DAYCARE, ACC. PRAYER ROOM, ACC. CHILDREN THEATER ROOM AND ACC. KITCHENETTE IN THE CELLAR AND AN EXISTING TWO FAMILY DWELLING ON THE SECOND FLOOR.          (FAST TRACK)      1
CERTIFICATE FOR A TAKE-OUT RESTAURANT IN SPACE A, IN THE SAME BUILDING WITH ANOTHER VACANT SPACE B, BOTH ON THE FIRST FLOOR AND A TWO (2) FAMILY DWELLING ABOVE.\r\n\r\n                                                                                                                                                                                                                                                                                                                    1
PERMIT FOR THE ERECTION OF A THREE(3) STORY ATTACHED STRUCTURE WITH CELLAR.  FOR  USE A A THREE(3) FAMILY DWELLING (NOT ADJUNCT TO ANY SCHOOLS, COLLEGES, UNIVERSITIES, AND OTHER INSTITUTIONS OF LEARNING).  SIZE AND LOCATION AS SHOWN IN THE APPLICATION.                                                                                                                                                                                                                                1
Name: appealgrounds, Length: 26523, dtype: int64

In [11]:
df['relatedpermit'].value_counts()

Description of Project:  PWD\n  APPEAL TYPES==> \nAPPEAL TYPE: WATER  \n\n  BOARD DECISIONS==> \n\n  COURT APPEALS==> \n                                                                                                                                                                 59
Description of Project:  TOBACCO\n  APPEAL TYPES==> \nAPPEAL TYPE:   \n\n  BOARD DECISIONS==> \n\n  COURT APPEALS==> \n                                                                                                                                                                  46
Description of Project:  SM/LRG FOOD ESTAB\n  APPEAL TYPES==> \nAPPEAL TYPE: LI-REFGRNT  \n\n  BOARD DECISIONS==> \nDECISION: CONTINUED  DECDATE: 16-OCT-18  PROVISO:   \n\n  COURT APPEALS==> \n                                                                                        30
Description of Project:  BUILDING PERMIT #765070\n  APPEAL TYPES==> \nAPPEAL TYPE: AGAINSTL&I  \n\n  BOARD DECISIONS==> \nDECISION: AFFIRMED  DECDATE: 28-JUL-17  PROVISO:   \n\n  COURT APPEALS==> \n                                                                                   28
Description of Project:  VENDING\n  APPEAL TYPES==> \nAPPEAL TYPE: BC-VIOL  \n\n  BOARD DECISIONS==> \n\n  COURT APPEALS==> \n                                                                                                                                                           21
                                                                                                                                                                                                                                                                                         ..
Description of Project:  240964\n  APPEAL TYPES==> \nAPPEAL TYPE: REFUSAL  \n\n  BOARD DECISIONS==> \nDECISION: APPROVED  DECDATE: 02-JUN-11  PROVISO:   \n\n  COURT APPEALS==> \n                                                                                                        1
Description of Project:  170165\n  APPEAL TYPES==> \nAPPEAL TYPE: HOUSING  \n\n  BOARD DECISIONS==> \nDECISION: AFFIRMED  DECDATE: 02-DEC-15  PROVISO: FOR WANT OF APPEARANCE  \n\n  COURT APPEALS==> \n                                                                                  1
Description of Project:  232770\n  APPEAL TYPES==> \nAPPEAL TYPE: AGAINSTL&I  \n\n  BOARD DECISIONS==> \nDECISION: CONTINUED  DECDATE: 30-JUN-10  PROVISO:   \nDECISION: MOOT  DECDATE: 25-AUG-10  PROVISO: COMPLIED  \n\n  COURT APPEALS==> \n                                           1
Description of Project:  241014\n  APPEAL TYPES==> \nAPPEAL TYPE: USEVAR  \nAPPEAL TYPE: ZONEVAR  \n\n  BOARD DECISIONS==> \nDECISION: GRANTED/PROV  DECDATE: 16-DEC-09  PROVISO: ***Proviso- letter of December 16, 2009 from Stephen G. Pollock, Esquire  \n\n  COURT APPEALS==> \n     1
Description of Project:  136545\n  APPEAL TYPES==> \nAPPEAL TYPE: USEVAR  \n\n  BOARD DECISIONS==> \nDECISION: DISMISSED  DECDATE: 13-AUG-08  PROVISO: *****CASE DISMISSED.*****  \n\n  COURT APPEALS==> \n                                                                               1
Name: relatedpermit, Length: 28217, dtype: int64

In [12]:
df['proviso'].value_counts()

COMPLIED                                                                              1752
FOR WANT OF APPEARANCE                                                                 738
*****CASE WITHDRAWN.*****                                                              402
*****CASE DISMISSED.*****                                                              163
ATTORNEY MOVING PARTY                                                                  155
                                                                                      ...
NO ROOF OR FURTHER ENCLOSURE.                                                            1
REVISED PLANS CONSISTING OF 2 PAGES STAMPED TODAY 1/10/18 BY ZBA                         1
***Proviso- letter dated February 17, 2012 from Old City Civic Association***            1
55 DAY STAY OF ENFORCEMENT                                                               1
Proviso-both units entering the property  from the first floor front of property**       1
Name: proviso, Length: 6779, dtype: int64