In [1]:
import os
import sqlite3
from sqlite3 import Error

In [2]:
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        #print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

In [3]:
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT *
        FROM FACILITIES
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)

In [4]:
def main():
    database = "data/sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2. Query all tasks
(0, 'Tennis Court 1', 5, 25, 10000, 200)
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(2, 'Badminton Court', 0, 15.5, 4000, 50)
(3, 'Table Tennis', 0, 5, 320, 10)
(4, 'Massage Room 1', 9.9, 80, 4000, 3000)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)
(6, 'Squash Court', 3.5, 17.5, 5000, 80)
(7, 'Snooker Table', 0, 5, 450, 15)
(8, 'Pool Table', 0, 5, 400, 15)

In [5]:
database = "data/sqlite_db_pythonsqlite.db"

# create a database connection
conn = create_connection(database)
cur = conn.cursor()

In [6]:
#Q10: Produce a list of facilities with a total revenue less than 1000.
    #The output of facility name and total revenue, sorted by revenue. Remember
    #that there's a different cost for guests and members! 
query1 = """
        with m as (
            SELECT f.facid, monthlymaintenance *
            (julianday(max(starttime)) - julianday(min(starttime)))/30 as totmaintenance
            from bookings b
            join facilities f 
            on b.facid = f.facid
            group by f.facid)
        select name,  
            round(sum(slots * (case when memid = 0 then guestcost
                          else membercost end)) - totmaintenance, 2) as totrevenue
        from bookings b
        join facilities f
            on b.facid = f.facid
        join m
            on m.facid = b.facid
        group by name
        having totrevenue < 1000
        order by totrevenue
        """
cur.execute(query1)
 
rows = cur.fetchall()
 
for row in rows:
    print(row)

('Table Tennis', 150.23)
('Snooker Table', 195.5)
('Pool Table', 225.3)

In [7]:
# Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order 
query1 = """
        SELECT m.firstname || ' ' || m.surname || ' recommended by ' || r.firstname || ' ' || r.surname
        FROM members m
        join members r
            on m.recommendedby = r.memid
        order by m.surname, m.firstname
        """
cur.execute(query1)
 
rows = cur.fetchall()
 
for row in rows:
    print(row)

('Florence Bader recommended by Ponder Stibbons',)
('Anne Baker recommended by Ponder Stibbons',)
('Timothy Baker recommended by Jemima Farrell',)
('Tim Boothe recommended by Tim Rownam',)
('Gerald Butters recommended by Darren Smith',)
('Joan Coplin recommended by Timothy Baker',)
('Erica Crumpet recommended by Tracy Smith',)
('Nancy Dare recommended by Janice Joplette',)
('Matthew Genting recommended by Gerald Butters',)
('John Hunt recommended by Millicent Purview',)
('David Jones recommended by Janice Joplette',)
('Douglas Jones recommended by David Jones',)
('Janice Joplette recommended by Darren Smith',)
('Anna Mackenzie recommended by Darren Smith',)
('Charles Owen recommended by Darren Smith',)
('David Pinker recommended by Jemima Farrell',)
('Millicent Purview recommended by Tracy Smith',)
('Henrietta Rumney recommended by Matthew Genting',)
('Ramnaresh Sarwin recommended by Florence Bader',)
('Jack Smith recommended by Darren Smith',)
('Ponder Stibbons recommended by Burton Tracy',)
('Henry Worthington-Smyth recommended by Tracy Smith',)

In [17]:
#Q12: Find the facilities with their usage by member, but not guests 
query1 = """
        SELECT name, firstname || ' ' || surname, sum(slots*.5)
        FROM facilities f
        join bookings b
            on f.facid = b.facid
        join members m
            on m.memid = b.memid
        where b.memid <> 0
        group by name, b.memid
        order by name, surname, firstname
        """
cur.execute(query1)
 
rows = cur.fetchall()
 
for row in rows:
    print(row)

('Badminton Court', 'Florence Bader', 13.5)
('Badminton Court', 'Anne Baker', 15.0)
('Badminton Court', 'Timothy Baker', 10.5)
('Badminton Court', 'Tim Boothe', 18.0)
('Badminton Court', 'Gerald Butters', 31.5)
('Badminton Court', 'Erica Crumpet', 3.0)
('Badminton Court', 'Nancy Dare', 15.0)
('Badminton Court', 'Jemima Farrell', 10.5)
('Badminton Court', 'John Hunt', 3.0)
('Badminton Court', 'David Jones', 12.0)
('Badminton Court', 'Douglas Jones', 3.0)
('Badminton Court', 'Anna Mackenzie', 48.0)
('Badminton Court', 'Charles Owen', 9.0)
('Badminton Court', 'David Pinker', 10.5)
('Badminton Court', 'Millicent Purview', 3.0)
('Badminton Court', 'Tim Rownam', 6.0)
('Badminton Court', 'Ramnaresh Sarwin', 10.5)
('Badminton Court', 'Darren Smith', 216.0)
('Badminton Court', 'Jack Smith', 18.0)
('Badminton Court', 'Tracy Smith', 51.0)
('Badminton Court', 'Ponder Stibbons', 24.0)
('Badminton Court', 'Burton Tracy', 3.0)
('Badminton Court', 'Hyacinth Tupperware', 1.5)
('Badminton Court', 'Henry Worthington-Smyth', 7.5)
('Massage Room 1', 'Anne Baker', 3.0)
('Massage Room 1', 'Timothy Baker', 25.0)
('Massage Room 1', 'Tim Boothe', 38.0)
('Massage Room 1', 'Gerald Butters', 33.0)
('Massage Room 1', 'Joan Coplin', 1.0)
('Massage Room 1', 'Erica Crumpet', 2.0)
('Massage Room 1', 'Nancy Dare', 19.0)
('Massage Room 1', 'Jemima Farrell', 34.0)
('Massage Room 1', 'Matthew Genting', 26.0)
('Massage Room 1', 'John Hunt', 3.0)
('Massage Room 1', 'David Jones', 20.0)
('Massage Room 1', 'Janice Joplette', 12.0)
('Massage Room 1', 'Anna Mackenzie', 1.0)
('Massage Room 1', 'Charles Owen', 11.0)
('Massage Room 1', 'David Pinker', 3.0)
('Massage Room 1', 'Tim Rownam', 88.0)
('Massage Room 1', 'Ramnaresh Sarwin', 8.0)
('Massage Room 1', 'Darren Smith', 29.0)
('Massage Room 1', 'Jack Smith', 27.0)
('Massage Room 1', 'Tracy Smith', 6.0)
('Massage Room 1', 'Ponder Stibbons', 20.0)
('Massage Room 1', 'Burton Tracy', 31.0)
('Massage Room 1', 'Hyacinth Tupperware', 1.0)
('Massage Room 1', 'Henry Worthington-Smyth', 1.0)
('Massage Room 2', 'Florence Bader', 2.0)
('Massage Room 2', 'Anne Baker', 2.0)
('Massage Room 2', 'Gerald Butters', 1.0)
('Massage Room 2', 'Joan Coplin', 2.0)
('Massage Room 2', 'Nancy Dare', 5.0)
('Massage Room 2', 'Matthew Genting', 1.0)
('Massage Room 2', 'David Jones', 4.0)
('Massage Room 2', 'Janice Joplette', 2.0)
('Massage Room 2', 'Charles Owen', 2.0)
('Massage Room 2', 'Tim Rownam', 2.0)
('Massage Room 2', 'Ramnaresh Sarwin', 3.0)
('Massage Room 2', 'Jack Smith', 1.0)
('Pool Table', 'Florence Bader', 11.5)
('Pool Table', 'Anne Baker', 6.0)
('Pool Table', 'Timothy Baker', 47.5)
('Pool Table', 'Tim Boothe', 13.0)
('Pool Table', 'Gerald Butters', 3.0)
('Pool Table', 'Joan Coplin', 5.5)
('Pool Table', 'Nancy Dare', 9.5)
('Pool Table', 'David Farrell', 12.5)
('Pool Table', 'Jemima Farrell', 0.5)
('Pool Table', 'Matthew Genting', 9.0)
('Pool Table', 'David Jones', 4.0)
('Pool Table', 'Douglas Jones', 1.0)
('Pool Table', 'Janice Joplette', 13.5)
('Pool Table', 'Anna Mackenzie', 41.5)
('Pool Table', 'Charles Owen', 0.5)
('Pool Table', 'David Pinker', 4.5)
('Pool Table', 'Millicent Purview', 2.5)
('Pool Table', 'Tim Rownam', 141.0)
('Pool Table', 'Henrietta Rumney', 1.5)
('Pool Table', 'Ramnaresh Sarwin', 6.5)
('Pool Table', 'Darren Smith', 14.0)
('Pool Table', 'Jack Smith', 3.5)
('Pool Table', 'Tracy Smith', 32.0)
('Pool Table', 'Ponder Stibbons', 6.0)
('Pool Table', 'Burton Tracy', 15.0)
('Pool Table', 'Hyacinth Tupperware', 4.5)
('Pool Table', 'Henry Worthington-Smyth', 18.5)
('Snooker Table', 'Florence Bader', 33.0)
('Snooker Table', 'Tim Boothe', 45.0)
('Snooker Table', 'Gerald Butters', 36.0)
('Snooker Table', 'Joan Coplin', 10.0)
('Snooker Table', 'Nancy Dare', 23.0)
('Snooker Table', 'David Farrell', 1.0)
('Snooker Table', 'Jemima Farrell', 22.0)
('Snooker Table', 'Matthew Genting', 1.0)
('Snooker Table', 'David Jones', 2.0)
('Snooker Table', 'Janice Joplette', 71.0)
('Snooker Table', 'Anna Mackenzie', 7.0)
('Snooker Table', 'Charles Owen', 22.0)
('Snooker Table', 'David Pinker', 16.0)
('Snooker Table', 'Millicent Purview', 1.0)
('Snooker Table', 'Henrietta Rumney', 14.0)
('Snooker Table', 'Ramnaresh Sarwin', 18.0)
('Snooker Table', 'Darren Smith', 12.0)
('Snooker Table', 'Jack Smith', 5.0)
('Snooker Table', 'Tracy Smith', 45.0)
('Snooker Table', 'Ponder Stibbons', 20.0)
('Snooker Table', 'Burton Tracy', 20.0)
('Snooker Table', 'Hyacinth Tupperware', 6.0)
('Squash Court', 'Florence Bader', 2.0)
('Squash Court', 'Anne Baker', 55.0)
('Squash Court', 'Timothy Baker', 5.0)
('Squash Court', 'Tim Boothe', 12.0)
('Squash Court', 'Gerald Butters', 9.0)
('Squash Court', 'Joan Coplin', 1.0)
('Squash Court', 'David Farrell', 1.0)
('Squash Court', 'Jemima Farrell', 8.0)
('Squash Court', 'John Hunt', 1.0)
('Squash Court', 'David Jones', 8.0)
('Squash Court', 'Douglas Jones', 1.0)
('Squash Court', 'Janice Joplette', 15.0)
('Squash Court', 'Anna Mackenzie', 2.0)
('Squash Court', 'Charles Owen', 7.0)
('Squash Court', 'David Pinker', 3.0)
('Squash Court', 'Millicent Purview', 1.0)
('Squash Court', 'Henrietta Rumney', 2.0)
('Squash Court', 'Ramnaresh Sarwin', 2.0)
('Squash Court', 'Darren Smith', 15.0)
('Squash Court', 'Jack Smith', 11.0)
('Squash Court', 'Tracy Smith', 6.0)
('Squash Court', 'Ponder Stibbons', 2.0)
('Squash Court', 'Burton Tracy', 39.0)
('Squash Court', 'Hyacinth Tupperware', 1.0)
('Table Tennis', 'Florence Bader', 43.0)
('Table Tennis', 'Anne Baker', 1.0)
('Table Tennis', 'Timothy Baker', 24.0)
('Table Tennis', 'Tim Boothe', 4.0)
('Table Tennis', 'Gerald Butters', 1.0)
('Table Tennis', 'Joan Coplin', 23.0)
('Table Tennis', 'Erica Crumpet', 2.0)
('Table Tennis', 'Nancy Dare', 5.0)
('Table Tennis', 'Jemima Farrell', 12.0)
('Table Tennis', 'Matthew Genting', 27.0)
('Table Tennis', 'John Hunt', 1.0)
('Table Tennis', 'David Jones', 11.0)
('Table Tennis', 'Janice Joplette', 9.0)
('Table Tennis', 'Anna Mackenzie', 16.0)
('Table Tennis', 'Charles Owen', 25.0)
('Table Tennis', 'David Pinker', 17.0)
('Table Tennis', 'Millicent Purview', 7.0)
('Table Tennis', 'Tim Rownam', 75.0)
('Table Tennis', 'Ramnaresh Sarwin', 3.0)
('Table Tennis', 'Darren Smith', 28.0)
('Table Tennis', 'Jack Smith', 5.0)
('Table Tennis', 'Tracy Smith', 28.0)
('Table Tennis', 'Ponder Stibbons', 3.0)
('Table Tennis', 'Burton Tracy', 24.0)
('Table Tennis', 'Henry Worthington-Smyth', 3.0)
('Tennis Court 1', 'Florence Bader', 1.5)
('Tennis Court 1', 'Anne Baker', 9.0)
('Tennis Court 1', 'Timothy Baker', 22.5)
('Tennis Court 1', 'Tim Boothe', 6.0)
('Tennis Court 1', 'Gerald Butters', 85.5)
('Tennis Court 1', 'Joan Coplin', 10.5)
('Tennis Court 1', 'Erica Crumpet', 1.5)
('Tennis Court 1', 'Nancy Dare', 40.5)
('Tennis Court 1', 'David Farrell', 9.0)
('Tennis Court 1', 'Jemima Farrell', 1.5)
('Tennis Court 1', 'Matthew Genting', 1.5)
('Tennis Court 1', 'John Hunt', 6.0)
('Tennis Court 1', 'David Jones', 42.0)
('Tennis Court 1', 'Douglas Jones', 13.5)
('Tennis Court 1', 'Janice Joplette', 28.5)
('Tennis Court 1', 'Charles Owen', 25.5)
('Tennis Court 1', 'David Pinker', 25.5)
('Tennis Court 1', 'Tim Rownam', 9.0)
('Tennis Court 1', 'Ramnaresh Sarwin', 7.5)
('Tennis Court 1', 'Jack Smith', 37.5)
('Tennis Court 1', 'Tracy Smith', 46.5)
('Tennis Court 1', 'Ponder Stibbons', 1.5)
('Tennis Court 1', 'Burton Tracy', 46.5)
('Tennis Court 2', 'Florence Bader', 12.0)
('Tennis Court 2', 'Anne Baker', 57.0)
('Tennis Court 2', 'Timothy Baker', 10.5)
('Tennis Court 2', 'Tim Boothe', 84.0)
('Tennis Court 2', 'Gerald Butters', 4.5)
('Tennis Court 2', 'Nancy Dare', 16.5)
('Tennis Court 2', 'David Farrell', 1.5)
('Tennis Court 2', 'Jemima Farrell', 1.5)
('Tennis Court 2', 'John Hunt', 6.0)
('Tennis Court 2', 'David Jones', 49.5)
('Tennis Court 2', 'Janice Joplette', 12.0)
('Tennis Court 2', 'Charles Owen', 70.5)
('Tennis Court 2', 'Millicent Purview', 1.5)
('Tennis Court 2', 'Tim Rownam', 9.0)
('Tennis Court 2', 'Henrietta Rumney', 1.5)
('Tennis Court 2', 'Ramnaresh Sarwin', 18.0)
('Tennis Court 2', 'Darren Smith', 28.5)
('Tennis Court 2', 'Jack Smith', 1.5)
('Tennis Court 2', 'Tracy Smith', 3.0)
('Tennis Court 2', 'Ponder Stibbons', 48.0)
('Tennis Court 2', 'Burton Tracy', 4.5)

In [20]:
#Q13: Find the facilities usage by month, but not guests 

#Q12: Find the facilities with their usage by member, but not guests 
query1 = """
        SELECT name, strftime('%m',starttime) as month, firstname || ' ' || surname, sum(slots*.5)
        FROM facilities f
        join bookings b
            on f.facid = b.facid
        join members m
            on m.memid = b.memid
        where b.memid <> 0
        group by name, month, b.memid
        order by name, month, surname, firstname
        """
cur.execute(query1)
 
rows = cur.fetchall()
 
for row in rows:
    print(row)

('Badminton Court', '07', 'Tim Boothe', 1.5)
('Badminton Court', '07', 'Gerald Butters', 6.0)
('Badminton Court', '07', 'Nancy Dare', 3.0)
('Badminton Court', '07', 'Tim Rownam', 1.5)
('Badminton Court', '07', 'Darren Smith', 61.5)
('Badminton Court', '07', 'Tracy Smith', 9.0)
('Badminton Court', '08', 'Florence Bader', 7.5)
('Badminton Court', '08', 'Anne Baker', 1.5)
('Badminton Court', '08', 'Timothy Baker', 4.5)
('Badminton Court', '08', 'Tim Boothe', 13.5)
('Badminton Court', '08', 'Gerald Butters', 13.5)
('Badminton Court', '08', 'Nancy Dare', 6.0)
('Badminton Court', '08', 'Jemima Farrell', 4.5)
('Badminton Court', '08', 'David Jones', 6.0)
('Badminton Court', '08', 'Anna Mackenzie', 4.5)
('Badminton Court', '08', 'Charles Owen', 6.0)
('Badminton Court', '08', 'David Pinker', 3.0)
('Badminton Court', '08', 'Tim Rownam', 1.5)
('Badminton Court', '08', 'Darren Smith', 90.0)
('Badminton Court', '08', 'Jack Smith', 9.0)
('Badminton Court', '08', 'Tracy Smith', 25.5)
('Badminton Court', '08', 'Ponder Stibbons', 9.0)
('Badminton Court', '08', 'Burton Tracy', 1.5)
('Badminton Court', '09', 'Florence Bader', 6.0)
('Badminton Court', '09', 'Anne Baker', 13.5)
('Badminton Court', '09', 'Timothy Baker', 6.0)
('Badminton Court', '09', 'Tim Boothe', 3.0)
('Badminton Court', '09', 'Gerald Butters', 12.0)
('Badminton Court', '09', 'Erica Crumpet', 3.0)
('Badminton Court', '09', 'Nancy Dare', 6.0)
('Badminton Court', '09', 'Jemima Farrell', 6.0)
('Badminton Court', '09', 'John Hunt', 3.0)
('Badminton Court', '09', 'David Jones', 6.0)
('Badminton Court', '09', 'Douglas Jones', 3.0)
('Badminton Court', '09', 'Anna Mackenzie', 43.5)
('Badminton Court', '09', 'Charles Owen', 3.0)
('Badminton Court', '09', 'David Pinker', 7.5)
('Badminton Court', '09', 'Millicent Purview', 3.0)
('Badminton Court', '09', 'Tim Rownam', 3.0)
('Badminton Court', '09', 'Ramnaresh Sarwin', 10.5)
('Badminton Court', '09', 'Darren Smith', 64.5)
('Badminton Court', '09', 'Jack Smith', 9.0)
('Badminton Court', '09', 'Tracy Smith', 16.5)
('Badminton Court', '09', 'Ponder Stibbons', 15.0)
('Badminton Court', '09', 'Burton Tracy', 1.5)
('Badminton Court', '09', 'Hyacinth Tupperware', 1.5)
('Badminton Court', '09', 'Henry Worthington-Smyth', 7.5)
('Massage Room 1', '07', 'Tim Boothe', 5.0)
('Massage Room 1', '07', 'Gerald Butters', 9.0)
('Massage Room 1', '07', 'Nancy Dare', 3.0)
('Massage Room 1', '07', 'Janice Joplette', 5.0)
('Massage Room 1', '07', 'Tim Rownam', 40.0)
('Massage Room 1', '07', 'Darren Smith', 14.0)
('Massage Room 1', '07', 'Tracy Smith', 3.0)
('Massage Room 1', '07', 'Burton Tracy', 4.0)
('Massage Room 1', '08', 'Anne Baker', 1.0)
('Massage Room 1', '08', 'Timothy Baker', 7.0)
('Massage Room 1', '08', 'Tim Boothe', 17.0)
('Massage Room 1', '08', 'Gerald Butters', 13.0)
('Massage Room 1', '08', 'Nancy Dare', 7.0)
('Massage Room 1', '08', 'Jemima Farrell', 10.0)
('Massage Room 1', '08', 'Matthew Genting', 2.0)
('Massage Room 1', '08', 'David Jones', 11.0)
('Massage Room 1', '08', 'Janice Joplette', 3.0)
('Massage Room 1', '08', 'Charles Owen', 8.0)
('Massage Room 1', '08', 'David Pinker', 1.0)
('Massage Room 1', '08', 'Tim Rownam', 25.0)
('Massage Room 1', '08', 'Darren Smith', 9.0)
('Massage Room 1', '08', 'Jack Smith', 11.0)
('Massage Room 1', '08', 'Tracy Smith', 1.0)
('Massage Room 1', '08', 'Ponder Stibbons', 14.0)
('Massage Room 1', '08', 'Burton Tracy', 18.0)
('Massage Room 1', '09', 'Anne Baker', 2.0)
('Massage Room 1', '09', 'Timothy Baker', 18.0)
('Massage Room 1', '09', 'Tim Boothe', 16.0)
('Massage Room 1', '09', 'Gerald Butters', 11.0)
('Massage Room 1', '09', 'Joan Coplin', 1.0)
('Massage Room 1', '09', 'Erica Crumpet', 2.0)
('Massage Room 1', '09', 'Nancy Dare', 9.0)
('Massage Room 1', '09', 'Jemima Farrell', 24.0)
('Massage Room 1', '09', 'Matthew Genting', 24.0)
('Massage Room 1', '09', 'John Hunt', 3.0)
('Massage Room 1', '09', 'David Jones', 9.0)
('Massage Room 1', '09', 'Janice Joplette', 4.0)
('Massage Room 1', '09', 'Anna Mackenzie', 1.0)
('Massage Room 1', '09', 'Charles Owen', 3.0)
('Massage Room 1', '09', 'David Pinker', 2.0)
('Massage Room 1', '09', 'Tim Rownam', 23.0)
('Massage Room 1', '09', 'Ramnaresh Sarwin', 8.0)
('Massage Room 1', '09', 'Darren Smith', 6.0)
('Massage Room 1', '09', 'Jack Smith', 16.0)
('Massage Room 1', '09', 'Tracy Smith', 2.0)
('Massage Room 1', '09', 'Ponder Stibbons', 6.0)
('Massage Room 1', '09', 'Burton Tracy', 9.0)
('Massage Room 1', '09', 'Hyacinth Tupperware', 1.0)
('Massage Room 1', '09', 'Henry Worthington-Smyth', 1.0)
('Massage Room 2', '07', 'Gerald Butters', 1.0)
('Massage Room 2', '07', 'Nancy Dare', 1.0)
('Massage Room 2', '07', 'Janice Joplette', 1.0)
('Massage Room 2', '07', 'Tim Rownam', 1.0)
('Massage Room 2', '08', 'Anne Baker', 2.0)
('Massage Room 2', '08', 'Nancy Dare', 2.0)
('Massage Room 2', '08', 'Matthew Genting', 1.0)
('Massage Room 2', '08', 'David Jones', 3.0)
('Massage Room 2', '08', 'Janice Joplette', 1.0)
('Massage Room 2', '09', 'Florence Bader', 2.0)
('Massage Room 2', '09', 'Joan Coplin', 2.0)
('Massage Room 2', '09', 'Nancy Dare', 2.0)
('Massage Room 2', '09', 'David Jones', 1.0)
('Massage Room 2', '09', 'Charles Owen', 2.0)
('Massage Room 2', '09', 'Tim Rownam', 1.0)
('Massage Room 2', '09', 'Ramnaresh Sarwin', 3.0)
('Massage Room 2', '09', 'Jack Smith', 1.0)
('Pool Table', '07', 'Tim Boothe', 0.5)
('Pool Table', '07', 'Gerald Butters', 1.0)
('Pool Table', '07', 'Nancy Dare', 1.0)
('Pool Table', '07', 'Janice Joplette', 5.0)
('Pool Table', '07', 'Tim Rownam', 34.5)
('Pool Table', '07', 'Darren Smith', 4.5)
('Pool Table', '07', 'Tracy Smith', 7.5)
('Pool Table', '07', 'Burton Tracy', 1.0)
('Pool Table', '08', 'Florence Bader', 4.0)
('Pool Table', '08', 'Anne Baker', 3.5)
('Pool Table', '08', 'Timothy Baker', 19.5)
('Pool Table', '08', 'Tim Boothe', 7.5)
('Pool Table', '08', 'Gerald Butters', 0.5)
('Pool Table', '08', 'Nancy Dare', 5.0)
('Pool Table', '08', 'Matthew Genting', 1.0)
('Pool Table', '08', 'David Jones', 2.5)
('Pool Table', '08', 'Janice Joplette', 6.5)
('Pool Table', '08', 'Anna Mackenzie', 4.0)
('Pool Table', '08', 'David Pinker', 2.0)
('Pool Table', '08', 'Tim Rownam', 58.5)
('Pool Table', '08', 'Darren Smith', 6.0)
('Pool Table', '08', 'Jack Smith', 2.5)
('Pool Table', '08', 'Tracy Smith', 15.0)
('Pool Table', '08', 'Ponder Stibbons', 3.5)
('Pool Table', '08', 'Burton Tracy', 10.0)
('Pool Table', '09', 'Florence Bader', 7.5)
('Pool Table', '09', 'Anne Baker', 2.5)
('Pool Table', '09', 'Timothy Baker', 28.0)
('Pool Table', '09', 'Tim Boothe', 5.0)
('Pool Table', '09', 'Gerald Butters', 1.5)
('Pool Table', '09', 'Joan Coplin', 5.5)
('Pool Table', '09', 'Nancy Dare', 3.5)
('Pool Table', '09', 'David Farrell', 12.5)
('Pool Table', '09', 'Jemima Farrell', 0.5)
('Pool Table', '09', 'Matthew Genting', 8.0)
('Pool Table', '09', 'David Jones', 1.5)
('Pool Table', '09', 'Douglas Jones', 1.0)
('Pool Table', '09', 'Janice Joplette', 2.0)
('Pool Table', '09', 'Anna Mackenzie', 37.5)
('Pool Table', '09', 'Charles Owen', 0.5)
('Pool Table', '09', 'David Pinker', 2.5)
('Pool Table', '09', 'Millicent Purview', 2.5)
('Pool Table', '09', 'Tim Rownam', 48.0)
('Pool Table', '09', 'Henrietta Rumney', 1.5)
('Pool Table', '09', 'Ramnaresh Sarwin', 6.5)
('Pool Table', '09', 'Darren Smith', 3.5)
('Pool Table', '09', 'Jack Smith', 1.0)
('Pool Table', '09', 'Tracy Smith', 9.5)
('Pool Table', '09', 'Ponder Stibbons', 2.5)
('Pool Table', '09', 'Burton Tracy', 4.0)
('Pool Table', '09', 'Hyacinth Tupperware', 4.5)
('Pool Table', '09', 'Henry Worthington-Smyth', 18.5)
('Snooker Table', '07', 'Tim Boothe', 4.0)
('Snooker Table', '07', 'Gerald Butters', 9.0)
('Snooker Table', '07', 'Nancy Dare', 2.0)
('Snooker Table', '07', 'Janice Joplette', 24.0)
('Snooker Table', '07', 'Darren Smith', 5.0)
('Snooker Table', '07', 'Tracy Smith', 22.0)
('Snooker Table', '07', 'Burton Tracy', 4.0)
('Snooker Table', '08', 'Florence Bader', 11.0)
('Snooker Table', '08', 'Tim Boothe', 24.0)
('Snooker Table', '08', 'Gerald Butters', 15.0)
('Snooker Table', '08', 'Nancy Dare', 10.0)
('Snooker Table', '08', 'Jemima Farrell', 15.0)
('Snooker Table', '08', 'David Jones', 2.0)
('Snooker Table', '08', 'Janice Joplette', 25.0)
('Snooker Table', '08', 'Charles Owen', 6.0)
('Snooker Table', '08', 'David Pinker', 7.0)
('Snooker Table', '08', 'Darren Smith', 3.0)
('Snooker Table', '08', 'Jack Smith', 2.0)
('Snooker Table', '08', 'Tracy Smith', 17.0)
('Snooker Table', '08', 'Ponder Stibbons', 9.0)
('Snooker Table', '08', 'Burton Tracy', 12.0)
('Snooker Table', '09', 'Florence Bader', 22.0)
('Snooker Table', '09', 'Tim Boothe', 17.0)
('Snooker Table', '09', 'Gerald Butters', 12.0)
('Snooker Table', '09', 'Joan Coplin', 10.0)
('Snooker Table', '09', 'Nancy Dare', 11.0)
('Snooker Table', '09', 'David Farrell', 1.0)
('Snooker Table', '09', 'Jemima Farrell', 7.0)
('Snooker Table', '09', 'Matthew Genting', 1.0)
('Snooker Table', '09', 'Janice Joplette', 22.0)
('Snooker Table', '09', 'Anna Mackenzie', 7.0)
('Snooker Table', '09', 'Charles Owen', 16.0)
('Snooker Table', '09', 'David Pinker', 9.0)
('Snooker Table', '09', 'Millicent Purview', 1.0)
('Snooker Table', '09', 'Henrietta Rumney', 14.0)
('Snooker Table', '09', 'Ramnaresh Sarwin', 18.0)
('Snooker Table', '09', 'Darren Smith', 4.0)
('Snooker Table', '09', 'Jack Smith', 3.0)
('Snooker Table', '09', 'Tracy Smith', 6.0)
('Snooker Table', '09', 'Ponder Stibbons', 11.0)
('Snooker Table', '09', 'Burton Tracy', 4.0)
('Snooker Table', '09', 'Hyacinth Tupperware', 6.0)
('Squash Court', '07', 'Tim Boothe', 1.0)
('Squash Court', '07', 'Gerald Butters', 3.0)
('Squash Court', '07', 'Janice Joplette', 7.0)
('Squash Court', '07', 'Darren Smith', 8.0)
('Squash Court', '07', 'Tracy Smith', 2.0)
('Squash Court', '07', 'Burton Tracy', 4.0)
('Squash Court', '08', 'Anne Baker', 25.0)
('Squash Court', '08', 'Timothy Baker', 2.0)
('Squash Court', '08', 'Tim Boothe', 6.0)
('Squash Court', '08', 'Gerald Butters', 4.0)
('Squash Court', '08', 'Jemima Farrell', 6.0)
('Squash Court', '08', 'David Jones', 4.0)
('Squash Court', '08', 'Janice Joplette', 3.0)
('Squash Court', '08', 'Charles Owen', 4.0)
('Squash Court', '08', 'David Pinker', 1.0)
('Squash Court', '08', 'Darren Smith', 6.0)
('Squash Court', '08', 'Jack Smith', 4.0)
('Squash Court', '08', 'Tracy Smith', 1.0)
('Squash Court', '08', 'Burton Tracy', 26.0)
('Squash Court', '09', 'Florence Bader', 2.0)
('Squash Court', '09', 'Anne Baker', 30.0)
('Squash Court', '09', 'Timothy Baker', 3.0)
('Squash Court', '09', 'Tim Boothe', 5.0)
('Squash Court', '09', 'Gerald Butters', 2.0)
('Squash Court', '09', 'Joan Coplin', 1.0)
('Squash Court', '09', 'David Farrell', 1.0)
('Squash Court', '09', 'Jemima Farrell', 2.0)
('Squash Court', '09', 'John Hunt', 1.0)
('Squash Court', '09', 'David Jones', 4.0)
('Squash Court', '09', 'Douglas Jones', 1.0)
('Squash Court', '09', 'Janice Joplette', 5.0)
('Squash Court', '09', 'Anna Mackenzie', 2.0)
('Squash Court', '09', 'Charles Owen', 3.0)
('Squash Court', '09', 'David Pinker', 2.0)
('Squash Court', '09', 'Millicent Purview', 1.0)
('Squash Court', '09', 'Henrietta Rumney', 2.0)
('Squash Court', '09', 'Ramnaresh Sarwin', 2.0)
('Squash Court', '09', 'Darren Smith', 1.0)
('Squash Court', '09', 'Jack Smith', 7.0)
('Squash Court', '09', 'Tracy Smith', 3.0)
('Squash Court', '09', 'Ponder Stibbons', 2.0)
('Squash Court', '09', 'Burton Tracy', 9.0)
('Squash Court', '09', 'Hyacinth Tupperware', 1.0)
('Table Tennis', '07', 'Janice Joplette', 1.0)
('Table Tennis', '07', 'Tim Rownam', 23.0)
('Table Tennis', '07', 'Darren Smith', 12.0)
('Table Tennis', '07', 'Tracy Smith', 13.0)
('Table Tennis', '08', 'Florence Bader', 13.0)
('Table Tennis', '08', 'Anne Baker', 1.0)
('Table Tennis', '08', 'Timothy Baker', 9.0)
('Table Tennis', '08', 'Tim Boothe', 4.0)
('Table Tennis', '08', 'Gerald Butters', 1.0)
('Table Tennis', '08', 'Nancy Dare', 4.0)
('Table Tennis', '08', 'Jemima Farrell', 4.0)
('Table Tennis', '08', 'Matthew Genting', 5.0)
('Table Tennis', '08', 'David Jones', 7.0)
('Table Tennis', '08', 'Janice Joplette', 6.0)
('Table Tennis', '08', 'Charles Owen', 19.0)
('Table Tennis', '08', 'David Pinker', 4.0)
('Table Tennis', '08', 'Tim Rownam', 33.0)
('Table Tennis', '08', 'Darren Smith', 9.0)
('Table Tennis', '08', 'Jack Smith', 3.0)
('Table Tennis', '08', 'Tracy Smith', 7.0)
('Table Tennis', '08', 'Ponder Stibbons', 1.0)
('Table Tennis', '08', 'Burton Tracy', 18.0)
('Table Tennis', '09', 'Florence Bader', 30.0)
('Table Tennis', '09', 'Timothy Baker', 15.0)
('Table Tennis', '09', 'Joan Coplin', 23.0)
('Table Tennis', '09', 'Erica Crumpet', 2.0)
('Table Tennis', '09', 'Nancy Dare', 1.0)
('Table Tennis', '09', 'Jemima Farrell', 8.0)
('Table Tennis', '09', 'Matthew Genting', 22.0)
('Table Tennis', '09', 'John Hunt', 1.0)
('Table Tennis', '09', 'David Jones', 4.0)
('Table Tennis', '09', 'Janice Joplette', 2.0)
('Table Tennis', '09', 'Anna Mackenzie', 16.0)
('Table Tennis', '09', 'Charles Owen', 6.0)
('Table Tennis', '09', 'David Pinker', 13.0)
('Table Tennis', '09', 'Millicent Purview', 7.0)
('Table Tennis', '09', 'Tim Rownam', 19.0)
('Table Tennis', '09', 'Ramnaresh Sarwin', 3.0)
('Table Tennis', '09', 'Darren Smith', 7.0)
('Table Tennis', '09', 'Jack Smith', 2.0)
('Table Tennis', '09', 'Tracy Smith', 8.0)
('Table Tennis', '09', 'Ponder Stibbons', 2.0)
('Table Tennis', '09', 'Burton Tracy', 6.0)
('Table Tennis', '09', 'Henry Worthington-Smyth', 3.0)
('Tennis Court 1', '07', 'Gerald Butters', 33.0)
('Tennis Court 1', '07', 'Nancy Dare', 9.0)
('Tennis Court 1', '07', 'Janice Joplette', 15.0)
('Tennis Court 1', '07', 'Tim Rownam', 6.0)
('Tennis Court 1', '07', 'Tracy Smith', 31.5)
('Tennis Court 1', '07', 'Burton Tracy', 6.0)
('Tennis Court 1', '08', 'Anne Baker', 4.5)
('Tennis Court 1', '08', 'Timothy Baker', 9.0)
('Tennis Court 1', '08', 'Tim Boothe', 6.0)
('Tennis Court 1', '08', 'Gerald Butters', 34.5)
('Tennis Court 1', '08', 'Nancy Dare', 19.5)
('Tennis Court 1', '08', 'David Jones', 12.0)
('Tennis Court 1', '08', 'Janice Joplette', 7.5)
('Tennis Court 1', '08', 'Charles Owen', 15.0)
('Tennis Court 1', '08', 'David Pinker', 6.0)
('Tennis Court 1', '08', 'Tim Rownam', 1.5)
('Tennis Court 1', '08', 'Jack Smith', 19.5)
('Tennis Court 1', '08', 'Tracy Smith', 9.0)
('Tennis Court 1', '08', 'Ponder Stibbons', 1.5)
('Tennis Court 1', '08', 'Burton Tracy', 24.0)
('Tennis Court 1', '09', 'Florence Bader', 1.5)
('Tennis Court 1', '09', 'Anne Baker', 4.5)
('Tennis Court 1', '09', 'Timothy Baker', 13.5)
('Tennis Court 1', '09', 'Gerald Butters', 18.0)
('Tennis Court 1', '09', 'Joan Coplin', 10.5)
('Tennis Court 1', '09', 'Erica Crumpet', 1.5)
('Tennis Court 1', '09', 'Nancy Dare', 12.0)
('Tennis Court 1', '09', 'David Farrell', 9.0)
('Tennis Court 1', '09', 'Jemima Farrell', 1.5)
('Tennis Court 1', '09', 'Matthew Genting', 1.5)
('Tennis Court 1', '09', 'John Hunt', 6.0)
('Tennis Court 1', '09', 'David Jones', 30.0)
('Tennis Court 1', '09', 'Douglas Jones', 13.5)
('Tennis Court 1', '09', 'Janice Joplette', 6.0)
('Tennis Court 1', '09', 'Charles Owen', 10.5)
('Tennis Court 1', '09', 'David Pinker', 19.5)
('Tennis Court 1', '09', 'Tim Rownam', 1.5)
('Tennis Court 1', '09', 'Ramnaresh Sarwin', 7.5)
('Tennis Court 1', '09', 'Jack Smith', 18.0)
('Tennis Court 1', '09', 'Tracy Smith', 6.0)
('Tennis Court 1', '09', 'Burton Tracy', 16.5)
('Tennis Court 2', '07', 'Tim Boothe', 9.0)
('Tennis Court 2', '07', 'Gerald Butters', 1.5)
('Tennis Court 2', '07', 'Nancy Dare', 6.0)
('Tennis Court 2', '07', 'Janice Joplette', 10.5)
('Tennis Court 2', '07', 'Tim Rownam', 7.5)
('Tennis Court 2', '07', 'Darren Smith', 22.5)
('Tennis Court 2', '07', 'Tracy Smith', 3.0)
('Tennis Court 2', '07', 'Burton Tracy', 1.5)
('Tennis Court 2', '08', 'Florence Bader', 4.5)
('Tennis Court 2', '08', 'Anne Baker', 24.0)
('Tennis Court 2', '08', 'Timothy Baker', 4.5)
('Tennis Court 2', '08', 'Tim Boothe', 40.5)
('Tennis Court 2', '08', 'Gerald Butters', 1.5)
('Tennis Court 2', '08', 'Nancy Dare', 10.5)
('Tennis Court 2', '08', 'Jemima Farrell', 1.5)
('Tennis Court 2', '08', 'David Jones', 19.5)
('Tennis Court 2', '08', 'Charles Owen', 34.5)
('Tennis Court 2', '08', 'Tim Rownam', 1.5)
('Tennis Court 2', '08', 'Darren Smith', 1.5)
('Tennis Court 2', '08', 'Ponder Stibbons', 25.5)
('Tennis Court 2', '08', 'Burton Tracy', 3.0)
('Tennis Court 2', '09', 'Florence Bader', 7.5)
('Tennis Court 2', '09', 'Anne Baker', 33.0)
('Tennis Court 2', '09', 'Timothy Baker', 6.0)
('Tennis Court 2', '09', 'Tim Boothe', 34.5)
('Tennis Court 2', '09', 'Gerald Butters', 1.5)
('Tennis Court 2', '09', 'David Farrell', 1.5)
('Tennis Court 2', '09', 'John Hunt', 6.0)
('Tennis Court 2', '09', 'David Jones', 30.0)
('Tennis Court 2', '09', 'Janice Joplette', 1.5)
('Tennis Court 2', '09', 'Charles Owen', 36.0)
('Tennis Court 2', '09', 'Millicent Purview', 1.5)
('Tennis Court 2', '09', 'Henrietta Rumney', 1.5)
('Tennis Court 2', '09', 'Ramnaresh Sarwin', 18.0)
('Tennis Court 2', '09', 'Darren Smith', 4.5)
('Tennis Court 2', '09', 'Jack Smith', 1.5)
('Tennis Court 2', '09', 'Ponder Stibbons', 22.5)